### ISSUE TITLE
Focus on aplication purpose

### ISSUE THREAD

**Issue by odahcam** [DanielRuf/swiper-builder#5]
The first time I openned the window, I thought that it was another CodePen or JSFiddle (code editor), I only realise the real purpose/objective/functionality of the app after find the options dialog.

Because of that, I think options should be shown by default and code outputs should come after, with less focus, otherwise visitor may think the app is a code editor.

**Comment by DanielRuf** [comment]
> Because of that, I think options should be shown by default and code outputs should come after, with less focus, otherwise visitor may think the app is a code editor.

You mean that swiper-builder should open the setting from the top by default?

**Comment by odahcam** [comment]
Yes, or even display things like https://jakearchibald.github.io/svgomg/ which shows you the preview and options and leaves code and etc for another step.

**Comment by DanielRuf** [comment]
This is not how it should work because it is meant for developers who have all the needed code visible at the same time to get the example working.

We are working with this for fast prototyping of swiper instances.

**Comment by odahcam** [comment]
Yeah, I understand, but for example, I will only want to see code when my Swiper is looking the way I want, if there's a way to temporary hide the code, I would surely use it.

**Comment by DanielRuf** [comment]
Souds like a feature request and another issue. Please create a new issue for this so I can properly track this.
